# Generated by Django 3.0.1 on 2020-03-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='Disease_speacialist',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='Related_disease',
        ),
        migrations.AddField(
            model_name='disease',
            name='Suggested_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicinesuggestions.Medicines'),
        ),
    ]
