# Generated by Django 3.0.1 on 2020-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
