# Generated by Django 3.0.1 on 2020-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0005_auto_20200321_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
