# Generated by Django 3.0.1 on 2020-05-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0006_auto_20200526_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='email',
        ),
    ]
