# Generated by Django 3.0.1 on 2020-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0007_remove_doctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
