# Generated by Django 3.0.1 on 2020-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinesuggestions', '0008_auto_20200526_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
